language: bash

sudo: required

env:
  global:
    - scr=/go/src/script
  matrix:
    - IMG="LINUX" KUBE=1
    - IMG="LINUX" KUBE=2
    - IMG="LINUX" KUBE=3
    - IMG="UNIX" KUBE=1
    - IMG="UNIX" KUBE=2
    - IMG="UNIX" KUBE=3
    - IMG="WIN" KUBE=1
    - IMG="WIN" KUBE=2
    - IMG="WIN" KUBE=3


script:
  - echo "Hello" 
  - ./test.sh $IMG

notifications:
  email:
    - dharnisingh@gmail.com
